(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var e,g="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},k=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},l=k(this),m;
if("function"==typeof Object.setPrototypeOf)m=Object.setPrototypeOf;else{var n;a:{var p={a:!0},q={};try{q.__proto__=p;n=q.a;break a}catch(a){}n=!1}m=n?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var r=m;var t="abort canplay canplaythrough durationchange emptied ended error loadeddata loadedmetadata loadstart pause play playing progress ratechange seeked seeking stalled suspend timeupdate volumechange waiting".split(" "),u={".avi":1,".m4v":1,".mp4":1,".mpeg":1,".mpg":1,".ogg":1,".ogv":1,".qt":1,".webm":1,".wmv":1};var v=function(a,b){window.setTimeout(a,b)};var w=function(a,b,c){c=void 0===c?null:c;var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,c);b.dispatchEvent(d)},x=function(a,b){var c=function(d){a.removeEventListener("playing",c);b(d)};a.addEventListener("playing",c)};var z=function(a){if(!a.gwdIsLoaded()){var b=y(a);b?b.gwdIsLoaded()&&a.gwdLoad():a.gwdLoad()}},A=function(a){if(!a.gwdIsActive()){var b=y(a);b?b.gwdIsActive()&&a.gwdActivate():a.gwdActivate()}},B=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},y=function(a){if(B(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&B(a))return a;return null},C=function(a){for(var b=[];a;)b.unshift(a),a=a.parentNode;return b},D=function(a,b,c){a.hasAttribute(b)?(a=a.getAttribute(b),
c.setAttribute(b,a)):c.removeAttribute(b)};var E={M:"fullscreenchange",N:"mozfullscreenchange",O:"webkitfullscreenchange"},F={M:"fullscreenElement",N:"mozFullScreenElement",O:"webkitFullscreenElement"},G=function(a){for(var b,c=Object.keys(F),d=0;d<c.length&&(b=a[F[c[d]]],void 0===b);d++);return b||null},H=function(a){var b=document;this.s="has-fullscreen-gwd-video";this.h=b;this.l=a;this.F=this.S.bind(this)};
H.prototype.S=function(){var a=G(this.h);if(a)if(this.l==a){var b=this.h;for(a=this.l;a&&a!=b;a=a.parentNode)a.classList.add(this.s)}else if(a.classList.contains(this.s)){b=C(this.l);a=C(a);for(var c=0,d=b[0],f=a[0],h=null;d&&f&&d==f;)h=d,c++,d=b[c],f=a[c];I(this,h)}else I(this);else I(this)};var I=function(a,b){b=(void 0===b?null:b)||a.h;for(var c=a.l;c&&c!=b;c=c.parentNode)c.classList.remove(a.s)};
H.prototype.install=function(){for(var a=Object.keys(E),b=0;b<a.length;b++)this.h.addEventListener(E[a[b]],this.F)};var J=Object.keys(HTMLMediaElement.prototype).concat(Object.keys(HTMLVideoElement.prototype)).concat(["sources"]),K=function(){var a=HTMLElement.call(this)||this;a.g=a.ownerDocument.createElement("video");a.g.setAttribute("webkit-playsinline","");a.g.setAttribute("playsinline","");a.g.setAttribute("x-webkit-airplay","allow");a.D=function(b){w(b.type,a,b.detail)};a.L=a.P.bind(a);a.G=new H(a.g);a.i=!1;a.j=null;a.o=null;a.interactiveVideoComponents=[];a.R=function(){for(var b=0;b<a.interactiveVideoComponents.length;b++)a.interactiveVideoComponents[b].handleVideoTimeUpdate()};
a.K=function(){a.j||(a.j=window.setInterval(a.R,33))};a.m=function(){a.j&&(window.clearInterval(a.j),a.j=null)};a.J=null;a.I=null;a.B=function(){if(a.parentElement){var b=a.getBoundingClientRect();if(b.width!=a.J||b.height!=a.I)for(a.J=b.width,a.I=b.height,b=0;b<a.interactiveVideoComponents.length;b++)a.interactiveVideoComponents[b].resizeHandlerNeeded&&a.interactiveVideoComponents[b].resize()}};a.T=function(){a.o||(a.o=window.setInterval(a.B,250))};a.U=function(){a.o&&window.clearInterval(a.o)};
a.v=!1;a.u=!1;a.H=!1;a.C=1;a.A=!1;return a},L=HTMLElement;K.prototype=g(L.prototype);K.prototype.constructor=K;if(r)r(K,L);else for(var M in L)if("prototype"!=M)if(Object.defineProperties){var N=Object.getOwnPropertyDescriptor(L,M);N&&Object.defineProperty(K,M,N)}else K[M]=L[M];e=K.prototype;
e.connectedCallback=function(){var a=this;if(!this.H){for(var b=0;b<this.children.length;b++){var c=this.children[b];if(c.classList.contains("intermediate-element")){this.removeChild(c);break}}this.i=this.muted&&-1!=(window.navigator.userAgent||"").indexOf("Android");b=this.ownerDocument.createElement("div");b.classList.add("intermediate-element");b.appendChild(this.g);this.appendChild(b);this.H=!0}z(this);A(this);this.i&&x(this.g,function(){a.i&&(a.g.volume=0)});this.g.addEventListener("volumechange",
this.L,!1);for(b=0;b<t.length;b++)this.g.addEventListener(t[b],this.D,!1);this.G.install();this.g.addEventListener("play",this.K,!1);this.g.addEventListener("pause",this.m,!1);this.g.addEventListener("ended",this.m,!1)};
e.disconnectedCallback=function(){for(var a=this.G,b=Object.keys(E),c=0;c<b.length;c++)a.h.removeEventListener(E[b[c]],a.F);b=G(a.h);a.l==b&&I(a);this.i&&(this.g.volume=1);this.g.removeEventListener("volumechange",this.L,!1);for(a=0;a<t.length;a++)this.g.removeEventListener(t[a],this.D,!1);this.m();this.g.removeEventListener("play",this.K,!1);this.g.removeEventListener("pause",this.m,!1);this.g.removeEventListener("ended",this.m,!1)};
e.setResizeObserver=function(){for(var a=!1,b=0;b<this.interactiveVideoComponents.length;b++)if(this.interactiveVideoComponents[b].resizeHandlerNeeded){a=!0;break}a?(this.T(),window.addEventListener("resize",this.B,!1)):(this.U(),window.removeEventListener("resize",this.B,!1))};
e.attributeChangedCallback=function(a){var b=this;if("sources"==a){if(this.v){var c=this.g.paused,d=this.muted;O(this);this.g.load();v(function(){b.muted=d;c?b.pause():b.play()},0)}}else"muted"==a&&(this.g.muted=this.muted);D(this,a,this.g)};e.gwdActivate=function(){var a=this;this.autoplay&&this.g.paused&&v(function(){if(2<=a.g.readyState)a.play();else{var b=function(){2<=a.g.readyState&&(a.g.removeEventListener("loadeddata",b),a.play())};a.g.addEventListener("loadeddata",b)}},200);this.u=!0};
e.gwdDeactivate=function(){this.hasAttribute("resumable")||this.seek(0);this.pause();this.u=!1};e.gwdIsActive=function(){return this.u};e.gwdLoad=function(){O(this);this.v=!0;w("ready",this)};e.gwdIsLoaded=function(){return this.v};e.play=function(){this.g.play()};e.pause=function(){this.g.pause()};e.mute=function(){this.i&&(this.g.volume=1);this.i=!1;this.muted=!this.muted};e.replay=function(){this.seek(0);this.play()};e.seek=function(a){this.currentTime!=a&&(this.currentTime=a)};
e.P=function(){0==this.A&&1==this.muted&&0==this.C&&(this.g.volume=1,this.muted=!1);this.C=this.g.volume;this.A=this.muted};e.setVolume=function(a){this.muted=0<a?!1:!0;this.g.volume=a/100;this.C=this.g.volume;this.A=this.muted};e.setSources=function(a){this.setAttribute("sources",a)};
var O=function(a){var b=a.getAttribute("sources");b=P(b);for(var c=a.g.children,d=c.length-1;0<=d;d--){var f=c[d];"source"==f.tagName.toLowerCase()&&a.g.removeChild(f)}for(c=0;c<b.length;c++)d=a.ownerDocument.createElement("source"),f=b[c],f=f.trim(),f=window.Enabler?window.Enabler.getUrl(f):f,d.src=f,a.g.appendChild(d)},P=function(a){var b=[];if(!a)return b;a=a.split(",").map(function(Q){return Q.trim()});for(var c="",d=0;d<a.length;d++){var f=a[d];c+=f;var h=f.lastIndexOf(".");-1!=h?u[f.substring(h).toLowerCase()]?
(b.push(c),c=""):c+=",":c+=","}c&&b.push(c.substring(0,c.length-1));return b};
l.Object.defineProperties(K.prototype,{nativeElement:{configurable:!0,enumerable:!0,get:function(){return this.g}},autoplay:{configurable:!0,enumerable:!0,get:function(){return this.g.autoplay},set:function(a){a?this.setAttribute("autoplay",""):this.removeAttribute("autoplay")}},loop:{configurable:!0,enumerable:!0,get:function(){return this.g.loop},set:function(a){a?this.setAttribute("loop",""):this.removeAttribute("loop")}},muted:{configurable:!0,enumerable:!0,get:function(){return this.hasAttribute("muted")},
set:function(a){a?this.setAttribute("muted",""):this.removeAttribute("muted")}},controls:{configurable:!0,enumerable:!0,get:function(){return this.g.controls},set:function(a){a?this.setAttribute("controls",""):this.removeAttribute("controls")}},poster:{configurable:!0,enumerable:!0,get:function(){return this.g.poster},set:function(a){a?this.setAttribute("poster",a):this.removeAttribute("poster")}},paused:{configurable:!0,enumerable:!0,get:function(){return this.g.paused}},volume:{configurable:!0,
enumerable:!0,get:function(){return this.g.volume},set:function(a){this.g.volume=a}},currentTime:{configurable:!0,enumerable:!0,get:function(){return this.g.currentTime},set:function(a){this.g.currentTime=a}},duration:{configurable:!0,enumerable:!0,get:function(){return this.g.duration}},width:{configurable:!0,enumerable:!0,get:function(){return this.g.width},set:function(a){a&&(this.g.width=a)}},height:{configurable:!0,enumerable:!0,get:function(){return this.g.height},set:function(a){a&&(this.g.height=
a)}},videoWidth:{configurable:!0,enumerable:!0,get:function(){return this.g.videoWidth}},videoHeight:{configurable:!0,enumerable:!0,get:function(){return this.g.videoHeight}}});l.Object.defineProperties(K,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return J}}});customElements.define("gwd-video",K);}).call(this);
